# Header
menu:
  首页: /
  # 标签: /tags
  归档: /archives
  关于: /about

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
github: danielhou09.github.io
local_search:
  enable: true          # 这个部分原来是false
search:
  path: search.xml
  field: post
  content: true

leancloud_visitors:
  enable: true
  app_id: Ibq54f164Xm1KrLhU9VLQbOU-gzGzoHsz
  app_key: YyFagCCh8AgXuinAsLfCQGhv

# Show PV/UV of the website/page with busuanzi. 不蒜子统计
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  # count values only if the other configs are false
  enable: false
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i> 访问人数
  site_uv_footer: 人次 
  # # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i> 总访问量
  site_pv_footer: 次 
  # custom pv span for one page only
  page_pv: false
  page_pv_header: <i class="fa fa-file-o"></i> 阅读
  page_pv_footer: 次 


baidu_anaylatic: a018bd1268619ff251e7d9038245a0ec


symbols_count_time:
  separated_meta: true     # 是否另起一行（true的话不和发表时间等同一行）
  item_text_post: true     # 首页文章统计数量前是否显示文字描述（本文字数、阅读时长）
  item_text_total: false   # 页面底部统计数量前是否显示文字描述（站点总字数、站点阅读时长）
  awl: 4                   # Average Word Length
  wpm: 275                 # Words Per Minute（每分钟阅读词数）
  suffix: mins.

post_wordcount: 		# 字数统计
  item_text: true		# 是否显示文字
  wordcount: true		# 显示字数
  min2read: true		# 显示阅读时间
  totalcount: true		# 显示总数
  separated_meta: true	# 是否分开

